### ISSUE TITLE
invalid rom

### ISSUE THREAD

**Issue by AsakuraFuuko** [enler/EmeraldRTCPatchTool#1]
> 8.23空之花神补完最终版

 和 

> 究极绿宝石V-LA-失落之古遗(正式版)

 会提示 invalid rom

**Comment by enler** [comment]
时间久远，不记得细节了，改版可能无法支持

**Comment by AsakuraFuuko** [comment]
https://github.com/enler/EmeraldRTCPatchTool/blob/21b5e11487fb0996938d9d1abc43976bff8ae8bd/patcher.cs#L105

> rom.Length <= emeraldRomMaxSize

试了下改成这样就可以了（
